# Generated by Django 5.1.2 on 2024-11-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsing_rezka", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rezka",
            name="image",
            field=models.URLField(null=True),
        ),
    ]
