# Generated by Django 5.1.2 on 2024-11-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_todo",
                    models.CharField(max_length=100, verbose_name="Укажите задачу"),
                ),
                ("time_start", models.TimeField(verbose_name="укажите время начала")),
                (
                    "time_end",
                    models.TimeField(verbose_name="укажите время конца задачи"),
                ),
                (
                    "check_yes_no",
                    models.CharField(
                        choices=[("✅", "✅"), ("❌", "❌")],
                        max_length=100,
                        verbose_name="укажите выполнено задача или нет",
                    ),
                ),
            ],
        ),
    ]
